services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pdrzan
    container_name: database
    restart: always
    ports:
      - 5431:5432
    volumes:
      - ./pData:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres -t 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s

  server:
    container_name: server
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - 8000:8000
      - 5000:5000
    depends_on:
      database:
        condition: service_healthy

  client:
    container_name: client
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    depends_on: 
      - server
